pr: none

resources:
  repositories:
  - repository: self
    type: github
    ref: main
    trigger:
    - main
    - vnext
  - repository: website
    type: github
    endpoint: Monaco
    name: microsoft/vscode-website
    ref: prod
  - repository: dist
    type: github
    endpoint: Monaco
    name: microsoft/vscode-website-dist
    ref: ${{ variables['Build.SourceBranch'] }}
jobs:
- job:
  displayName: Build
  variables:
    skipComponentGovernanceDetection: true
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted macOS
  steps:
  - checkout: website
    clean: true
    path: vscode-website
    persistCredentials: true
    fetchDepth: 1
  - checkout: self
    path: vscode-website/vscode-docs
    lfs: true
    fetchDepth: 1
    persistCredentials: true
  - checkout: dist
    path: vscode-website/dist
    fetchDepth: 1
    persistCredentials: true
  - task: NodeTool@0
    displayName: Use Node 12.18.0
    inputs:
      versionSpec: 12.18.0
      checkLatest: true
  - task: Npm@0
    displayName: npm install yarn
    inputs:
      arguments: -g yarn
  - task: CmdLine@1
    displayName: yarn install
    inputs:
      filename: yarn
      arguments: install
      workingFolder: ../vscode-website
  - task: Bash@3
    displayName: Build Dist Setup
    inputs:
      filePath: ../vscode-website/scripts/ci-build-dist-setup.sh
      workingDirectory: ../vscode-website
    env:
      WEBSITE_BRANCH: $(Build.SourceBranchName)
  - task: Bash@3
    displayName: Rebuild Dist From Website
    condition: eq(variables['Build.Repository.Name'], 'microsoft/vscode-website')
    inputs:
      filePath: ../vscode-website/scripts/ci-build-dist-from-website.sh
      workingDirectory: ../vscode-website
    env:
      WEBSITE_BRANCH: $(Build.SourceBranchName)
  - task: Bash@3
    displayName: Rebuild Dist From Docs
    condition: eq(variables['Build.Repository.Name'], 'microsoft/vscode-docs')
    inputs:
      filePath: ../vscode-website/scripts/ci-build-dist-from-docs.sh
      workingDirectory: ../vscode-website
    env:
      DOCS_BRANCH: $(Build.SourceBranchName)